# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Desafio Pitang' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift',      '~> 4.0'
  pod 'RxCocoa',      '~> 4.0'
  pod 'Moya/RxSwift', '~> 11.0'
  pod 'Nuke',         '~> 7.0'

  # Pods for Desafio Pitang

end
